/** LCP hero image paths and dimensions (generated by scripts/optimize-hero.mjs). */
export const HERO_LCP = {
  webpSrc: "/images/hero-1280.webp",
  jpgSrc: "/images/hero-1280.jpg",
  srcSet:
    "/images/hero-640.webp 640w, /images/hero-960.webp 960w, /images/hero-1280.webp 1280w, /images/hero-1920.webp 1920w",
  sizes: "(max-width: 640px) 100vw, (max-width: 1024px) 100vw, 1280px",
  width: 1280,
  height: 800,
  preloadHref: "/images/hero-960.webp",
} as const;
