/** LCP hero image paths and dimensions (generated by scripts/optimize-hero.mjs). */
export const HERO_LCP = {
  avifSrcSet:
    "/images/hero-480.avif 480w, /images/hero-768.avif 768w, /images/hero-960.webp 960w, /images/hero-1280.webp 1280w",
  webpSrcSet:
    "/images/hero-480.webp 480w, /images/hero-640.webp 640w, /images/hero-768.webp 768w, /images/hero-960.webp 960w, /images/hero-1280.webp 1280w",
  jpgSrc: "/images/hero-1280.jpg",
  sizes: "(max-width: 640px) 100vw, (max-width: 1024px) 100vw, 1280px",
  width: 1280,
  height: 800,
  /** Mobile-first preload — matches ~640px viewport WebP LCP candidate. */
  preloadHref: "/images/hero-640.webp",
  preloadSrcSet:
    "/images/hero-480.webp 480w, /images/hero-640.webp 640w, /images/hero-768.webp 768w",
  preloadSizes: "100vw",
} as const;
