/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FounderRouteImport } from './routes/founder'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthInitiateRouteImport } from './routes/auth.initiate'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminNewsletterRouteImport } from './routes/admin/newsletter'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderRoute = FounderRouteImport.update({
  id: '/founder',
  path: '/founder',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthInitiateRoute = AuthInitiateRouteImport.update({
  id: '/initiate',
  path: '/initiate',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/founder': typeof FounderRoute
  '/gallery': typeof GalleryRoute
  '/partner': typeof PartnerRoute
  '/programs': typeof ProgramsRoute
  '/resources': typeof ResourcesRoute
  '/team': typeof TeamRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/initiate': typeof AuthInitiateRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/founder': typeof FounderRoute
  '/gallery': typeof GalleryRoute
  '/partner': typeof PartnerRoute
  '/programs': typeof ProgramsRoute
  '/resources': typeof ResourcesRoute
  '/team': typeof TeamRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/initiate': typeof AuthInitiateRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/founder': typeof FounderRoute
  '/gallery': typeof GalleryRoute
  '/partner': typeof PartnerRoute
  '/programs': typeof ProgramsRoute
  '/resources': typeof ResourcesRoute
  '/team': typeof TeamRoute
  '/volunteer': typeof VolunteerRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/initiate': typeof AuthInitiateRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/donate'
    | '/events'
    | '/founder'
    | '/gallery'
    | '/partner'
    | '/programs'
    | '/resources'
    | '/team'
    | '/volunteer'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/messages'
    | '/admin/newsletter'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/initiate'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/donate'
    | '/events'
    | '/founder'
    | '/gallery'
    | '/partner'
    | '/programs'
    | '/resources'
    | '/team'
    | '/volunteer'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/messages'
    | '/admin/newsletter'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/initiate'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/donate'
    | '/events'
    | '/founder'
    | '/gallery'
    | '/partner'
    | '/programs'
    | '/resources'
    | '/team'
    | '/volunteer'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/messages'
    | '/admin/newsletter'
    | '/admin/settings'
    | '/admin/users'
    | '/auth/callback'
    | '/auth/initiate'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  FounderRoute: typeof FounderRoute
  GalleryRoute: typeof GalleryRoute
  PartnerRoute: typeof PartnerRoute
  ProgramsRoute: typeof ProgramsRoute
  ResourcesRoute: typeof ResourcesRoute
  TeamRoute: typeof TeamRoute
  VolunteerRoute: typeof VolunteerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder': {
      id: '/founder'
      path: '/founder'
      fullPath: '/founder'
      preLoaderRoute: typeof FounderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/initiate': {
      id: '/auth/initiate'
      path: '/initiate'
      fullPath: '/auth/initiate'
      preLoaderRoute: typeof AuthInitiateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthInitiateRoute: typeof AuthInitiateRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthInitiateRoute: AuthInitiateRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  FounderRoute: FounderRoute,
  GalleryRoute: GalleryRoute,
  PartnerRoute: PartnerRoute,
  ProgramsRoute: ProgramsRoute,
  ResourcesRoute: ResourcesRoute,
  TeamRoute: TeamRoute,
  VolunteerRoute: VolunteerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
