// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { logMissingSupabaseEnvOnce, readSupabasePublicEnv } from "@/lib/env";

function createSupabaseClient() {
  const { url, anonKey, isConfigured } = readSupabasePublicEnv();

  if (!isConfigured) {
    logMissingSupabaseEnvOnce();
  }

  // Never throw during client construction — misconfigured env should degrade
  // gracefully (empty data / user-visible errors) instead of crashing the app.
  return createClient<Database>(
    url || "https://invalid.supabase.co",
    anonKey || "invalid-anon-key",
    {
      auth: {
        storage: typeof window !== "undefined" ? localStorage : undefined,
        persistSession: isConfigured,
        autoRefreshToken: isConfigured,
        detectSessionInUrl: isConfigured,
        flowType: "pkce",
      },
    },
  );
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export function isSupabaseConfigured() {
  return readSupabasePublicEnv().isConfigured;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
